server.port=8081

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres-auth:5432/auth_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:auth_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:auth_pass}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL:false}
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

eureka.client.service-url.defaultZone=${EUREKA_DEFAULT_ZONE:http://eureka-server:8761/eureka}
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true

jwt.secret=${JWT_SECRET}
jwt.expiration=86400000

logging.level.org.springframework.security=${SECURITY_LOG_LEVEL:INFO}
logging.level.pe.edu.upeu.auth_service=${APP_LOG_LEVEL:INFO}

management.endpoints.web.exposure.include=health,info,metrics,circuitbreakers,circuitbreakerevents
management.endpoint.health.show-details=when_authorized
management.health.circuitbreakers.enabled=true