server.port=8085

spring.datasource.url=${DB_URL:jdbc:postgresql://postgres-messaging:5432/messaging_db}
spring.datasource.username=${DB_USERNAME:messaging_user}
spring.datasource.password=${DB_PASSWORD:messaging_pass}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL:false}
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

eureka.client.service-url.defaultZone=${EUREKA_DEFAULT_ZONE:http://eureka-server:8761/eureka}
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always