    # Spring Boot Basic
    spring.application.name=auth-service
    server.port=8081
    server.error.include-message=always
    server.error.include-binding-errors=always

      # Base de datos (PostgreSQL)
    spring.datasource.url=jdbc:postgresql://localhost:5432/auth_db
    spring.datasource.username=auth_user
    spring.datasource.password=auth_pass
    spring.datasource.driver-class-name=org.postgresql.Driver

      # JPA / Hibernate
    spring.jpa.hibernate.ddl-auto=update
    spring.jpa.show-sql=true
    spring.jpa.properties.hibernate.format_sql=true
    spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

      # Eureka Client
    eureka.client.service-url.defaultZone=http://localhost:8761/eureka
    eureka.client.register-with-eureka=true
    eureka.client.fetch-registry=true
    eureka.instance.prefer-ip-address=true

      # JWT Configuration
    jwt.secret=clave_secreta_super_larga_para_jwt_minimo_32_caracteres_seguridad!
    jwt.expiration=86400000

      # Logging
    logging.level.org.springframework.security=DEBUG
    logging.level.pe.edu.upeu.auth_service=DEBUG

      # Actuator (monitoreo + Circuit Breaker)
    management.endpoints.web.exposure.include=health,info,metrics,circuitbreakers,circuitbreakerevents
    management.endpoint.health.show-details=when_authorized
    management.health.circuitbreakers.enabled=true

      # Resilience4j Circuit Breaker
    resilience4j.circuitbreaker.instances.auth-service.registerHealthIndicator=true
    resilience4j.circuitbreaker.instances.auth-service.slidingWindowSize=10
    resilience4j.circuitbreaker.instances.auth-service.failureRateThreshold=50
    resilience4j.circuitbreaker.instances.auth-service.waitDurationInOpenState=10s
    resilience4j.circuitbreaker.instances.auth-service.permittedNumberOfCallsInHalfOpenState=3
    resilience4j.circuitbreaker.instances.auth-service.automaticTransitionFromOpenToHalfOpenEnabled=true
    resilience4j.timelimiter.instances.auth-service.timeoutDuration=3s