spring.application.name=notification-service
server.port=8086

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5435/notification_db}
spring.datasource.username=${DB_USERNAME:notification_user}
spring.datasource.password=${DB_PASSWORD:notification_pass}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

eureka.client.service-url.defaultZone=${EUREKA_DEFAULT_ZONE:http://localhost:8761/eureka}
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true

spring.kafka.bootstrap-servers=${KAFKA_SERVERS:localhost:9092}
spring.kafka.consumer.group-id=notification-service
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.value.default.type=java.util.Map
spring.kafka.consumer.properties.spring.json.trusted.packages=*

management.endpoints.web.exposure.include=health,info,metrics,circuitbreakers,circuitbreakerevents
management.endpoint.health.show-details=when_authorized
management.health.circuitbreakers.enabled=true

resilience4j.circuitbreaker.instances.notification-service.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.notification-service.slidingWindowSize=10
resilience4j.circuitbreaker.instances.notification-service.failureRateThreshold=50
resilience4j.circuitbreaker.instances.notification-service.waitDurationInOpenState=10s
resilience4j.circuitbreaker.instances.notification-service.permittedNumberOfCallsInHalfOpenState=3
resilience4j.circuitbreaker.instances.notification-service.automaticTransitionFromOpenToHalfOpenEnabled=true

resilience4j.retry.instances.notification-service.maxAttempts=3
resilience4j.retry.instances.notification-service.waitDuration=1s
resilience4j.retry.instances.notification-service.enableExponentialBackoff=true

logging.level.org.springframework.security=DEBUG
logging.level.pe.edu.upeu.notification_service=DEBUG