spring.application.name=api-gateway
server.port=8080

eureka.client.service-url.defaultZone=${EUREKA_DEFAULT_ZONE:http://localhost:8761/eureka}
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true

spring.cloud.gateway.mvc.routes[0].id=auth-service
spring.cloud.gateway.mvc.routes[0].uri=lb://auth-service
spring.cloud.gateway.mvc.routes[0].predicates[0]=Path=/api/auth/**

spring.cloud.gateway.mvc.routes[1].id=product-service-products
spring.cloud.gateway.mvc.routes[1].uri=lb://product-service
spring.cloud.gateway.mvc.routes[1].predicates[0]=Path=/api/productos/**

spring.cloud.gateway.mvc.routes[2].id=product-service-categories
spring.cloud.gateway.mvc.routes[2].uri=lb://product-service
spring.cloud.gateway.mvc.routes[2].predicates[0]=Path=/api/categorias/**

spring.cloud.gateway.mvc.routes[3].id=order-service
spring.cloud.gateway.mvc.routes[3].uri=lb://order-service
spring.cloud.gateway.mvc.routes[3].predicates[0]=Path=/api/pedidos/**

spring.cloud.gateway.mvc.routes[4].id=payment-service
spring.cloud.gateway.mvc.routes[4].uri=lb://payment-service
spring.cloud.gateway.mvc.routes[4].predicates[0]=Path=/api/pagos/**

spring.cloud.gateway.mvc.routes[5].id=messaging-service
spring.cloud.gateway.mvc.routes[5].uri=lb://messaging-service
spring.cloud.gateway.mvc.routes[5].predicates[0]=Path=/api/mensajes/**

spring.cloud.gateway.mvc.routes[6].id=notification-service
spring.cloud.gateway.mvc.routes[6].uri=lb://notification-service
spring.cloud.gateway.mvc.routes[6].predicates[0]=Path=/api/notificaciones/**

spring.cloud.gateway.mvc.routes[7].id=review-service
spring.cloud.gateway.mvc.routes[7].uri=lb://review-service
spring.cloud.gateway.mvc.routes[7].predicates[0]=Path=/api/resenas/**

spring.cloud.gateway.mvc.routes[8].id=recommendation-service
spring.cloud.gateway.mvc.routes[8].uri=lb://recommendation-service
spring.cloud.gateway.mvc.routes[8].predicates[0]=Path=/api/recomendaciones/**

management.endpoints.web.exposure.include=health,info,gateway
