spring:
  application:
    name: product-service

  # PostgreSQL
  datasource:
    url: jdbc:postgresql://localhost:5433/product_db
    username: postgres
    password: oracle123
    driver-class-name: org.postgresql.Driver

  # JPA / Hibernate
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  # Redis
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000ms

  # Cache
  cache:
    type: redis
    redis:
      time-to-live: 600000   # 10 minutos en ms

# Puerto del microservicio
server:
  port: 8082

# Eureka Client
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

# Actuator
management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics

# Springdoc / Swagger
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html