spring.application.name=review-service
server.port=8088

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5437/review_db}
spring.datasource.username=${DB_USERNAME:review_user}
spring.datasource.password=${DB_PASSWORD:review_pass}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

eureka.client.service-url.defaultZone=${EUREKA_DEFAULT_ZONE:http://localhost:8761/eureka}
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true

spring.kafka.bootstrap-servers=${KAFKA_SERVERS:localhost:9092}
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

management.endpoints.web.exposure.include=health,info

resilience4j.circuitbreaker.instances.pedidoService.register-health-indicator=true
resilience4j.circuitbreaker.instances.pedidoService.sliding-window-size=10
resilience4j.circuitbreaker.instances.pedidoService.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.pedidoService.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.pedidoService.permitted-number-of-calls-in-half-open-state=3
resilience4j.retry.instances.pedidoService.max-attempts=3
resilience4j.retry.instances.pedidoService.wait-duration=500ms
